# Generated by Django 6.0.3 on 2026-03-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourMateriel',
            fields=[
                ('id_retour', models.AutoField(primary_key=True, serialize=False)),
                ('date_retour', models.DateField(auto_now_add=True)),
                ('motif_retour', models.CharField(choices=[('panne', 'panne'), ('inutilise', 'inutilise'), ('endommage', 'endommage'), ('autre', 'autre')], max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('', ''), ('repare', 'repare'), ('non_repare', 'non_repare'), ('rebut', 'rebut'), ('reaffecte', 'reaffecte')], default='', max_length=20)),
                ('justification_decision', models.TextField(blank=True)),
                ('observation', models.TextField(blank=True)),
                ('id_instance_ressource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.instanceressource')),
                ('id_ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ressource')),
            ],
            options={
                'verbose_name': 'retour materiel',
                'verbose_name_plural': 'retours materiel',
            },
        ),
    ]
