# Generated by Django 6.0.3 on 2026-03-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('returns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='retourmateriel',
            name='id_retourne_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_soumis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retourmateriel',
            name='id_traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_traites', to=settings.AUTH_USER_MODEL),
        ),
    ]
