# Generated by Django 6.0.5 on 2026-05-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0005_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retourmateriel',
            name='decision',
            field=models.CharField(blank=True, choices=[('', ''), ('hors_service', 'hors_service'), ('en_stock', 'en_stock'), ('repare', 'repare'), ('non_repare', 'non_repare'), ('rebut', 'rebut'), ('reaffecte', 'reaffecte')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='retourmateriel',
            name='motif_retour',
            field=models.CharField(choices=[('panne', 'panne'), ('inutilise', 'inutilise'), ('endommage', 'endommage'), ('autre', 'autre')], max_length=20),
        ),
    ]
