# Generated by Django 6.0.3 on 2026-05-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0006_add_endommage_autre_motifs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retourmateriel',
            name='decision',
            field=models.CharField(blank=True, choices=[('', ''), ('hors_service', 'hors_service'), ('en_stock', 'en_stock'), ('repare', 'repare'), ('debarras', 'debarras'), ('reaffecte', 'reaffecte')], default='', max_length=20),
        ),
    ]
