# Generated by Django 6.0.3 on 2026-03-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('resources', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importexcelbc',
            name='id_importe_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotarticle',
            name='id_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ressource'),
        ),
        migrations.AddField(
            model_name='marchebc',
            name='id_cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marchebc',
            name='id_fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.fournisseur'),
        ),
        migrations.AddField(
            model_name='lotarticle',
            name='id_marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='procurement.marchebc'),
        ),
        migrations.AddField(
            model_name='importexcelbc',
            name='id_marche',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_excel', to='procurement.marchebc'),
        ),
        migrations.AddField(
            model_name='marcheetape',
            name='id_marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='procurement.marchebc'),
        ),
        migrations.AddField(
            model_name='marcheetape',
            name='id_modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagingitem',
            name='id_categorie_suggeree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.categorie'),
        ),
        migrations.AddField(
            model_name='stagingitem',
            name='id_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_items', to='procurement.importexcelbc'),
        ),
        migrations.AddField(
            model_name='stagingitem',
            name='id_ressource_liee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ressource'),
        ),
        migrations.AlterUniqueTogether(
            name='lotarticle',
            unique_together={('id_marche', 'numero_lot')},
        ),
    ]
