# Generated by Django 6.0.3 on 2026-04-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_import_title_and_staging_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingitem',
            name='categorie_suggeree_nom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stagingitem',
            name='sous_categorie_suggeree_nom',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
