# Generated by Django 6.0.3 on 2026-04-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_stagingitem_categorie_suggeree_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagingitem',
            name='confiance_ia',
        ),
    ]
