# Generated by Django 6.0.3 on 2026-04-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_import_title_and_staging_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagingitem',
            name='confiance_ia',
        ),
    ]
