# Generated by Django 6.0.3 on 2026-04-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_stagingitem_reject_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingitem',
            name='motif_rejet',
            field=models.CharField(blank=True, choices=[('en_attente_livraison', 'en_attente_livraison'), ('non_conforme', 'non_conforme'), ('autre', 'autre')], default='', max_length=40),
        ),
    ]
