# Generated by Django 6.0.3 on 2026-04-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_marchebc_donor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchebc',
            name='contact_donateur',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='marchebc',
            name='nom_donateur',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='marchebc',
            name='organisme_donateur',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='marchebc',
            name='type_donateur',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
