# Generated by Django 6.0.3 on 2026-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_harmonize_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchebc',
            name='contact_donateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marchebc',
            name='nom_donateur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marchebc',
            name='organisme_donateur',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='marchebc',
            name='type_donateur',
            field=models.CharField(blank=True, choices=[('interne', 'Interne (enseignant, decanat...)'), ('externe', 'Externe (association, organisation internationale...)')], max_length=20, null=True),
        ),
    ]
