# Generated by Django 6.0.5 on 2026-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0016_remove_non_conforme_marche'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchebc',
            name='motif_rejet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='marchebc',
            name='statut',
            field=models.CharField(choices=[('en_attente_livraison', 'en_attente_livraison'), ('receptionne_et_stocke', 'receptionne_et_stocke'), ('refuse', 'refuse')], db_index=True, default='en_attente_livraison', max_length=30),
        ),
    ]
