# Generated by Django 6.0.3 on 2026-05-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_marchebc_comite_conformite_marchebc_date_attribution_and_more'),
        ('procurement', '0019_alter_stagingitem_categorie_fk'),
    ]

    operations = [
    ]
