# Generated by Django 6.0.3 on 2026-05-21 19:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0020_merge_20260521_1332'),
        ('resources', '0029_backfill_statut_debarras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotarticle',
            name='id_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.ressource'),
        ),
        migrations.AlterField(
            model_name='marcheetape',
            name='nom_etape',
            field=models.CharField(choices=[('marche_cree', 'marche_cree'), ('contrat_signe', 'contrat_signe'), ('en_attente_livraison', 'en_attente_livraison'), ('livraison_en_cours', 'livraison_en_cours'), ('receptionne_magasin', 'receptionne_magasin'), ('controle_qualite', 'controle_qualite'), ('bl_valide', 'bl_valide'), ('stocker_au_magasin', 'stocker_au_magasin'), ('paiement_en_cours', 'paiement_en_cours'), ('paiement_effectue', 'paiement_effectue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='marcheetape',
            name='ordre',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
