# Generated by Django 6.0.3 on 2026-03-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteDelai',
            fields=[
                ('id_alerte', models.AutoField(primary_key=True, serialize=False)),
                ('date_echeance', models.DateField()),
                ('niveau_alerte', models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('critique', 'critique')], max_length=20)),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('penalite_applicable', models.BooleanField(default=False)),
                ('acquitte', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'alerte delai',
                'verbose_name_plural': 'alertes delai',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('type_action', models.CharField(max_length=100)),
                ('table_cible', models.CharField(max_length=100)),
                ('id_enregistrement_cible', models.IntegerField()),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': "journal d'audit",
                'verbose_name_plural': "journaux d'audit",
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('type_notification', models.CharField(choices=[('alerte_stock', 'alerte_stock'), ('alerte_delai', 'alerte_delai'), ('demande_soumise', 'demande_soumise'), ('decharge_prete', 'decharge_prete'), ('scan_recu', 'scan_recu'), ('validation_requise', 'validation_requise')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('canal', models.CharField(choices=[('web', 'web'), ('email', 'email')], default='web', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
            },
        ),
    ]
