# Generated by Django 6.0.3 on 2026-03-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertedelai',
            name='id_marche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='procurement.marchebc'),
        ),
    ]
