# Generated by Django 6.0.3 on 2026-05-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_envoi',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='id_destinataire',
            new_name='destinataire',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date_lecture',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='niveau',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='info', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='objet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('demande_soumise', 'Demande soumise'), ('demande_validee', 'Demande validée'), ('demande_rejetee', 'Demande rejetée'), ('decharge_generee', 'Décharge générée'), ('decharge_signee', 'Décharge signée'), ('retour_enregistre', 'Retour enregistré'), ('alerte_stock', 'Alerte stock')], default='alerte_stock', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
