# Generated by Django 6.0.3 on 2026-05-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='niveau',
            field=models.CharField(choices=[('info', 'Info'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Danger')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('demande_soumise', 'Demande soumise'), ('demande_validee', 'Demande validée'), ('demande_rejetee', 'Demande rejetée'), ('decharge_generee', 'Décharge générée'), ('decharge_signee', 'Décharge signée'), ('retour_enregistre', 'Retour enregistré'), ('alerte_stock', 'Alerte stock')], default='alerte_stock', max_length=30),
        ),
    ]
