# Generated by Django 6.0.5 on 2026-05-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_seed_dentistry_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id_batiment', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'bâtiment',
                'verbose_name_plural': 'bâtiments',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id_etablissement', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissements',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='id_batiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='users.batiment'),
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id_beneficiaire', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('role_type', models.CharField(choices=[('chef_service', 'Chef de Service'), ('fonctionnaire', 'Fonctionnaire'), ('secretariat', 'Secrétariat'), ('salle_de_cours', 'Salle de cours'), ('prof', 'Prof')], max_length=30)),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires', to='users.service')),
            ],
            options={
                'verbose_name': 'bénéficiaire',
                'verbose_name_plural': 'bénéficiaires',
            },
        ),
        migrations.AddField(
            model_name='batiment',
            name='id_etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='users.etablissement'),
        ),
        migrations.AlterUniqueTogether(
            name='batiment',
            unique_together={('nom', 'id_etablissement')},
        ),
    ]
