# Generated by Django 6.0.5 on 2026-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_seed_hierarchy_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nom_role',
            field=models.CharField(choices=[('service_financiere', 'service_financiere'), ('gestionnaire_magasin', 'gestionnaire_magasin'), ('chef_service', 'chef_service'), ('admin', 'admin')], max_length=100, unique=True),
        ),
    ]
