# Generated by Django 6.0.5 on 2026-05-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_remove_disponibilite_pct'),
        ('users', '0007_etablissement_batiment_beneficiaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='id_beneficiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='users.beneficiaire'),
        ),
    ]
