# Generated by Django 6.0.3 on 2026-05-21 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_demande_statut_refactor'),
        ('resources', '0029_backfill_statut_debarras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='id_chef_demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lignedemande',
            name='id_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.ressource'),
        ),
    ]
