# Generated by Django 6.0.3 on 2026-05-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0012_protect_fk_on_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='beneficiaire_detail',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='beneficiaire_nom',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='beneficiaire_type',
        ),
    ]
