# Generated by Django 6.0.3 on 2026-03-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(choices=[('Consommable', 'Consommable'), ('Bien Inventaire', 'Bien Inventaire')], max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id_mouvement', models.AutoField(primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('entree', 'entree'), ('sortie', 'sortie'), ('retour', 'retour'), ('transfert', 'transfert'), ('rebut', 'rebut')], max_length=50)),
                ('quantite', models.IntegerField()),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'mouvement de stock',
                'verbose_name_plural': 'mouvements de stock',
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id_ressource', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unite_mesure', models.CharField(default='unité', max_length=20)),
            ],
            options={
                'verbose_name': 'ressource',
                'verbose_name_plural': 'ressources',
            },
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id_sous_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sous_categorie', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'sous-categorie',
                'verbose_name_plural': 'sous-categories',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_disponible', models.IntegerField(default=0)),
                ('quantite_reservee', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=5)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='InstanceRessource',
            fields=[
                ('id_instance', models.AutoField(primary_key=True, serialize=False)),
                ('numero_inventaire', models.CharField(max_length=50, unique=True)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('valeur_acquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('en_stock', 'en_stock'), ('en_service', 'en_service'), ('en_maintenance', 'en_maintenance'), ('hors_service', 'hors_service'), ('retire', 'retire')], default='en_stock', max_length=50)),
                ('etat', models.CharField(choices=[('neuf', 'neuf'), ('bon_etat', 'bon_etat'), ('usage_normal', 'usage_normal'), ('endommage', 'endommage'), ('hors_service', 'hors_service')], default='neuf', max_length=50)),
                ('localisation_actuelle', models.CharField(blank=True, max_length=200)),
                ('date_derniere_affectation', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True)),
                ('id_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='procurement.lotarticle')),
            ],
            options={
                'verbose_name': 'instance ressource',
                'verbose_name_plural': 'instances ressource',
            },
        ),
    ]
