# Generated by Django 6.0.3 on 2026-03-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('resources', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceressource',
            name='id_service_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.service'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='id_instance_ressource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.instanceressource'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='id_utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ressource',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.categorie'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='id_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ressource'),
        ),
        migrations.AddField(
            model_name='instanceressource',
            name='id_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ressource'),
        ),
        migrations.AddField(
            model_name='souscategorie',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.categorie'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='id_sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.souscategorie'),
        ),
        migrations.AddField(
            model_name='stock',
            name='id_ressource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resources.ressource'),
        ),
    ]
