# Generated by Django 6.0.3 on 2026-04-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceressource',
            name='id_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='resources.ressource'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='id_ressource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ressource'),
        ),
    ]
