# Generated by Django 6.0.3 on 2026-04-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_instanceressource_id_ressource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscategorie',
            name='id_parent_sous_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resources.souscategorie'),
        ),
        migrations.AlterField(
            model_name='instanceressource',
            name='id_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ressource'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='id_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ressource'),
        ),
    ]
