# Generated by Django 6.0.3 on 2026-04-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_instanceressource_numero_inventaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceressource',
            name='numero_inventaire',
            field=models.CharField(blank=True, help_text='Auto-generated in format INV-{YY}-{XXXX} if omitted', max_length=50, unique=True),
        ),
    ]
