# Generated by Django 6.0.3 on 2026-04-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_cleanup_souscategorie_hierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscategorie',
            name='id_parent_sous_categorie',
        ),
    ]
