# Generated by Django 6.0.3 on 2026-05-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_purge_noncanoincal_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceressource',
            name='numero_inventaire',
            field=models.CharField(blank=True, help_text='Auto-generated in format INV-{YYYY}-{XXXX} if omitted', max_length=50, unique=True),
        ),
    ]
