# Generated by Django 6.0.3 on 2026-05-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_ressource_seuil_alerte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceressource',
            name='etat',
            field=models.CharField(choices=[('neuf', 'neuf'), ('bon_etat', 'bon_etat'), ('usage_normal', 'usage_normal'), ('endommage', 'endommage'), ('hors_service', 'hors_service'), ('retourne', 'retourne')], default='neuf', max_length=50),
        ),
    ]
