# Generated by Django 6.0.3 on 2026-05-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_alter_instanceressource_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='seuil_alerte',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='seuil_alerte',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
