# Generated by Django 6.0.3 on 2026-05-21 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_categorie_date_mise_a_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceressource',
            name='statut',
            field=models.CharField(choices=[('en_stock', 'en_stock'), ('en_service', 'en_service'), ('en_maintenance', 'en_maintenance'), ('debarras', 'debarras')], db_index=True, default='en_stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='souscategorie',
            name='id_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.categorie'),
        ),
        migrations.AlterField(
            model_name='typearticle',
            name='nom_categorie',
            field=models.CharField(choices=[('consommable', 'Consommable'), ('bien_inventaire', 'Bien Inventaire')], max_length=200),
        ),
    ]
