# Generated by Django 6.0.3 on 2026-05-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0029_backfill_statut_debarras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_disponible__gte', 0)), name='stock_quantite_disponible_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_reservee__lte', models.F('quantite_disponible'))), name='stock_quantite_reservee_lte_disponible'),
        ),
    ]
