# Generated by Django 6.0.3 on 2026-05-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_stock_constraints_and_positive_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='seuil_alerte',
        ),
    ]
