# Generated by Django 6.0.3 on 2026-03-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decharge',
            fields=[
                ('id_decharge', models.AutoField(primary_key=True, serialize=False)),
                ('numero_decharge', models.CharField(max_length=50, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='decharges/pdf/')),
                ('observation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'decharge',
                'verbose_name_plural': 'decharges',
            },
        ),
        migrations.CreateModel(
            name='LigneDecharge',
            fields=[
                ('id_ligne_decharge', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.IntegerField()),
                ('type_ligne', models.CharField(choices=[('bien_inventaire', 'bien_inventaire'), ('consommable', 'consommable')], max_length=20)),
                ('observation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ligne de decharge',
                'verbose_name_plural': 'lignes de decharge',
            },
        ),
        migrations.CreateModel(
            name='SignatureDecharge',
            fields=[
                ('id_signature', models.AutoField(primary_key=True, serialize=False)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('fichier_scan_signe', models.FileField(blank=True, null=True, upload_to='decharges/scans/')),
                ('observation_chef', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'en_attente'), ('signe', 'signe'), ('valide', 'valide'), ('rejete', 'rejete')], default='en_attente', max_length=20)),
                ('date_validation_systeme', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'signature de decharge',
                'verbose_name_plural': 'signatures de decharge',
            },
        ),
    ]
