# Generated by Django 6.0.3 on 2026-03-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decharge', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decharge',
            name='id_demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decharge', to='requests.demande'),
        ),
    ]
