# Generated by Django 6.0.3 on 2026-03-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decharge', '0002_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decharge',
            name='id_genere_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decharges_generees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decharge',
            name='id_livre_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decharges_livrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lignedecharge',
            name='id_decharge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='decharge.decharge'),
        ),
        migrations.AddField(
            model_name='lignedecharge',
            name='id_instance_ressource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.instanceressource'),
        ),
        migrations.AddField(
            model_name='lignedecharge',
            name='id_ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.ressource'),
        ),
        migrations.AddField(
            model_name='signaturedecharge',
            name='id_chef_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures_soumises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturedecharge',
            name='id_decharge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='decharge.decharge'),
        ),
        migrations.AddField(
            model_name='signaturedecharge',
            name='id_valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='lignedecharge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('id_instance_ressource__isnull', False), ('type_ligne', 'bien_inventaire')), models.Q(('id_instance_ressource__isnull', True), ('type_ligne', 'consommable')), _connector='OR'), name='decharge_instance_required_by_type'),
        ),
    ]
