from rest_framework import serializers

from .models import Decharge, LigneDecharge, SignatureDecharge


# ---------------------------------------------------------------------------
# Nested read helpers
# ---------------------------------------------------------------------------


class _RessourceBriefSerializer(serializers.Serializer):
    id_ressource = serializers.IntegerField()
    designation = serializers.CharField()
    unite_mesure = serializers.CharField()


class _InstanceBriefSerializer(serializers.Serializer):
    id_instance = serializers.IntegerField()
    numero_inventaire = serializers.CharField()
    statut = serializers.CharField()
    etat = serializers.CharField()


class _UtilisateurBriefSerializer(serializers.Serializer):
    id_utilisateur = serializers.IntegerField()
    nom_complet = serializers.CharField()


# ---------------------------------------------------------------------------
# LigneDecharge
# ---------------------------------------------------------------------------


class LigneDechargeSerializer(serializers.ModelSerializer):
    ressource = _RessourceBriefSerializer(source="id_ressource", read_only=True)
    instance_ressource = _InstanceBriefSerializer(
        source="id_instance_ressource", read_only=True
    )

    class Meta:
        model = LigneDecharge
        fields = [
            "id_ligne_decharge",
            "quantite",
            "type_ligne",
            "observation",
            "id_decharge",
            "id_ressource",
            "ressource",
            "id_instance_ressource",
            "instance_ressource",
        ]
        read_only_fields = ["id_ligne_decharge", "id_decharge"]


# ---------------------------------------------------------------------------
# Decharge — full read
# ---------------------------------------------------------------------------


class DechargeSerializer(serializers.ModelSerializer):
    lignes = LigneDechargeSerializer(many=True, read_only=True)
    statut_signature = serializers.CharField(read_only=True)
    date_signature = serializers.SerializerMethodField()
    genere_par = _UtilisateurBriefSerializer(source="id_genere_par", read_only=True)

    def get_date_signature(self, obj):
        try:
            return obj.signature.date_signature
        except Exception:
            return None

    class Meta:
        model = Decharge
        fields = [
            "id_decharge",
            "numero_decharge",
            "date_generation",
            "date_livraison",
            "fichier_pdf",
            "observation",
            "id_demande",
            "id_genere_par",
            "genere_par",
            "id_livre_a",
            "statut_signature",
            "date_signature",
            "lignes",
        ]
        read_only_fields = [
            "id_decharge",
            "numero_decharge",
            "date_generation",
            "fichier_pdf",
            "statut_signature",
            "date_signature",
        ]


# ---------------------------------------------------------------------------
# Decharge — create
# ---------------------------------------------------------------------------


class _LigneDechargeCreateSerializer(serializers.Serializer):
    id_ressource = serializers.IntegerField()
    quantite = serializers.IntegerField(min_value=1)
    type_ligne = serializers.ChoiceField(
        choices=LigneDecharge.TYPE_LIGNE_CHOICES
    )
    id_instance_ressource = serializers.IntegerField(required=False, allow_null=True)


class DechargeCreateSerializer(serializers.ModelSerializer):
    lignes = _LigneDechargeCreateSerializer(many=True, write_only=True)

    class Meta:
        model = Decharge
        fields = [
            "id_demande",
            "date_livraison",
            "observation",
            "id_livre_a",
            "lignes",
        ]

    def validate(self, attrs):
        demande = attrs.get("id_demande")
        if demande and demande.statut not in ("partielle", "totale"):
            raise serializers.ValidationError(
                {
                    "id_demande": (
                        f"La demande doit etre au statut 'partielle' ou 'totale' pour creer une decharge "
                        f"(statut actuel : '{demande.statut}')."
                    )
                }
            )
        return attrs

    def create(self, validated_data):
        lignes_data = validated_data.pop("lignes")
        # numero_decharge is auto-generated by Decharge.save()
        decharge = Decharge.objects.create(**validated_data)

        lignes_bulk = []
        for ld in lignes_data:
            lignes_bulk.append(
                LigneDecharge(
                    id_decharge=decharge,
                    id_ressource_id=ld["id_ressource"],
                    quantite=ld["quantite"],
                    type_ligne=ld["type_ligne"],
                    id_instance_ressource_id=ld.get("id_instance_ressource"),
                )
            )
        LigneDecharge.objects.bulk_create(lignes_bulk)

        # Trigger the PDF generation task after the Decharge is persisted.
        from apps.decharge.tasks import generate_decharge_pdf  # noqa: PLC0415

        generate_decharge_pdf.delay(decharge.pk)
        return decharge


# ---------------------------------------------------------------------------
# SignatureDecharge
# ---------------------------------------------------------------------------


class SignatureDechargeSerializer(serializers.ModelSerializer):
    fichier_scan_signe = serializers.FileField(required=False, allow_null=True)

    class Meta:
        model = SignatureDecharge
        fields = [
            "id_signature",
            "date_signature",
            "fichier_scan_signe",
            "observation_chef",
            "statut",
            "date_validation_systeme",
            "id_decharge",
            "id_chef_service",
            "id_valide_par",
        ]
        read_only_fields = [
            "id_signature",
            "date_signature",
            "statut",
            "date_validation_systeme",
            "id_decharge",
            "id_valide_par",
        ]
